#!/usr/bin/env python3
"""Generate embedded_assets.generated.cpp from a built frontend/dist tree.

Each file under --dist-dir is gzip-compressed and emitted as a
`static const unsigned char[]` byte array (not a string literal, to avoid
MSVC's 64 KB string-literal limit), keyed by its request path in the
EMBEDDED_ASSETS[] table declared in src/include/embedded_assets.hpp.
"""
import argparse
import gzip
import os
import sys

BYTES_PER_LINE = 20


def emit_byte_array(name, data, out):
    out.write(f"static const unsigned char {name}[] = {{\n")
    for i in range(0, len(data), BYTES_PER_LINE):
        chunk = data[i : i + BYTES_PER_LINE]
        out.write("  " + ",".join(str(b) for b in chunk) + ",\n")
    out.write("};\n")


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--dist-dir", required=True, help="frontend/dist directory")
    parser.add_argument("--output", required=True, help="path to write the generated .cpp")
    args = parser.parse_args()

    dist_dir = args.dist_dir
    entries = []
    for root, _dirs, files in os.walk(dist_dir):
        for fname in files:
            full = os.path.join(root, fname)
            rel = "/" + os.path.relpath(full, dist_dir).replace(os.sep, "/")
            entries.append((rel, full))
    entries.sort()

    if not entries:
        sys.exit(f"error: no files found under {dist_dir} -- did you run `make frontend`?")

    with open(args.output, "w") as out:
        out.write("// Generated by scripts/generate_embedded_assets.py. Do not edit.\n")
        out.write('#include "embedded_assets.hpp"\n\n')
        out.write("namespace duckdb {\nnamespace ui {\n\n")

        for i, (_rel, full) in enumerate(entries):
            with open(full, "rb") as f:
                raw = f.read()
            compressed = gzip.compress(raw, compresslevel=9, mtime=0)
            emit_byte_array(f"kEmbeddedAssetData{i}", compressed, out)
            out.write("\n")

        out.write("const EmbeddedAsset EMBEDDED_ASSETS[] = {\n")
        for i, (rel, _full) in enumerate(entries):
            out.write(
                f'  {{"{rel}", kEmbeddedAssetData{i}, sizeof(kEmbeddedAssetData{i})}},\n'
            )
        out.write("};\n\n")
        out.write(
            "const size_t EMBEDDED_ASSETS_COUNT = "
            "sizeof(EMBEDDED_ASSETS) / sizeof(EMBEDDED_ASSETS[0]);\n\n"
        )
        out.write("} // namespace ui\n} // namespace duckdb\n")


if __name__ == "__main__":
    main()
